language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run build
after_success:
  - git config --global user.name "kewalkothari"
  - git config --global user.email "kewalkothari@users.noreply.github.com"
  - git remote rm origin
  - git remote add origin https://kewalkothari:${GH_TOKEN}@github.com/kewalkothari/live-stock-media-net.git
  - npm run deploy
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master